data = {"markets": [
    {'market': '1INCH-EUR', 'status': 'trading', 'base': '1INCH',
     'quote': 'EUR', 'pricePrecision': 5, 'minOrderInBaseAsset': '2',
     'minOrderInQuoteAsset': '5',
     'orderTypes': ['market', 'limit', 'stopLoss', 'stopLossLimit',
                    'takeProfit', 'takeProfitLimit']},
    {'market': 'AAVE-EUR', 'status': 'trading', 'base': 'AAVE', 'quote': 'EUR',
     'pricePrecision': 5, 'minOrderInBaseAsset': '0.008',
     'minOrderInQuoteAsset': '5',
     'orderTypes': ['market', 'limit', 'stopLoss', 'stopLossLimit',
                    'takeProfit', 'takeProfitLimit']},
    {'market': 'ADA-BTC', 'status': 'halted', 'base': 'ADA', 'quote': 'BTC',
     'pricePrecision': 5, 'minOrderInBaseAsset': '10',
     'minOrderInQuoteAsset': '0.001',
     'orderTypes': ['market', 'limit', 'stopLoss', 'stopLossLimit',
                    'takeProfit', 'takeProfitLimit']},
    {'market': 'ADA-EUR', 'status': 'trading', 'base': 'ADA', 'quote': 'EUR',
     'pricePrecision': 5, 'minOrderInBaseAsset': '3',
     'minOrderInQuoteAsset': '5',
     'orderTypes': ['market', 'limit', 'stopLoss', 'stopLossLimit',
                    'takeProfit', 'takeProfitLimit']}]}
